# Generated by Django 3.2.8 on 2021-11-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CREATOR', 'Creator'), ('SUBSCRIBER', 'Subscriber')], max_length=30, null=True),
        ),
    ]
