# Generated by Django 3.2.8 on 2021-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211101_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='authentication\\static\x07uthentication\\images\\default-user.jpg', upload_to=''),
        ),
    ]
